name: Build Eaglercraft
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Run Build
        shell: cmd
        run: |
          :: gradlew.bat を探して実行するよ
          for /f "delims=" %%i in ('dir /s /b gradlew.bat') do (
              cd /d "%%~dpi"
              
              :: 空白が入らないように、直接JAVA_HOMEをダブルクォートで囲って伝えるよ
              call gradlew.bat build --no-daemon "-Dorg.gradle.java.home=%JAVA_HOME%"
              exit /b
          )
          
      - name: Search and Upload
        uses: actions/upload-artifact@v4
        with:
          name: eaglercraft-build
          # 成果物がどこにできてもいいように、広めに拾う設定にしたよ
          path: |
            **/index.html
            **/classes.js
            **/assets/
            **/lang/
            **/build/distributions/
            **/stable-download/
